# fly.toml app configuration file generated for datingappacl on 2023-05-19T16:09:10-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "datingappacl"
primary_region = "lax"

[build]
  image = "abelardocruzleos/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="ddjs4le7k"
  CloudinarySettings__ApiKey="945941883263387"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
